# Generated by Django 5.1.4 on 2025-01-06 01:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_rename_image_prod_producto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShopPed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_car_ped', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Cart Pedido',
                'verbose_name_plural': 'Cart Pedidos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_sale', models.DateTimeField(verbose_name='Fecha de pedido')),
                ('date_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad de Productos')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('type_invoce', models.CharField(choices=[('0', 'Boleta'), ('1', 'Factura'), ('2', 'Sin Comprobante')], max_length=2, verbose_name='TIPO')),
                ('type_payment', models.CharField(choices=[('0', 'Transferencia'), ('1', 'Efectivo')], max_length=2, verbose_name='TIPO PAGO')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento')),
                ('entregado', models.BooleanField(default=False, verbose_name='Pedido entregado')),
                ('anulate', models.BooleanField(default=False, verbose_name='Pedido Anulado')),
                ('cliente_nombre', models.CharField(max_length=50, verbose_name='nombre del cliente')),
                ('cliente_celular', models.CharField(max_length=50, verbose_name='nombre del cliente')),
                ('cliente_carnet', models.CharField(max_length=50, verbose_name='carnet del cliente')),
                ('adelanto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='adelanto')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='adelanto')),
                ('cliente_departamento', models.CharField(blank=True, max_length=50, verbose_name='departamento del cliente')),
                ('cliente_direccion', models.CharField(blank=True, max_length=70, verbose_name='direccion de delivery')),
                ('cliente_sucursal', models.CharField(blank=True, max_length=50, verbose_name='sucursal de envio del cliente')),
                ('description', models.TextField(blank=True, verbose_name='descripcion del pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pedido', to=settings.AUTH_USER_MODEL, verbose_name='Admin Pedido')),
            ],
            options={
                'verbose_name': 'Peido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price_purchase', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio Compra')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto')),
                ('anulate', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False, verbose_name='Pedido entregado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sale', to='pedidos.pedido', verbose_name='Codigo de Venta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pedido', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Producto Vendido',
                'verbose_name_plural': 'Productos vendidos',
            },
        ),
    ]
