# Generated by Django 5.1.4 on 2025-01-06 01:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carshopped',
            options={'ordering': ['-created'], 'verbose_name': 'CartShop Pedido', 'verbose_name_plural': 'CartShop Pedidos'},
        ),
        migrations.AlterField(
            model_name='carshopped',
            name='barcode',
            field=models.CharField(max_length=13),
        ),
        migrations.CreateModel(
            name='CartP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Carrito activo')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_ped', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cart Pedido',
                'verbose_name_plural': 'Cart Pedidos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='carshopped',
            name='cart',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.cartp', verbose_name='Carrito'),
        ),
    ]
