# Generated by Django 5.1.4 on 2025-01-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_carshopped_options_alter_carshopped_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodetail',
            name='price_purchase',
        ),
    ]
