# Generated by Django 5.1.4 on 2025-01-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedidodetail_price_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshopped',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
