# Generated by Django 5.1.4 on 2025-01-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_carshopped_precio_total'),
        ('productos', '0006_alter_producto_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshopped',
            name='extras',
            field=models.ManyToManyField(blank=True, to='productos.extra'),
        ),
    ]
