# Generated by Django 5.1.4 on 2025-01-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_carshopped_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='saldo'),
        ),
    ]
