# Generated by Django 5.1.4 on 2025-01-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='type_entrega',
            field=models.CharField(choices=[('0', 'Entrega en Tienda'), ('1', 'Envio'), ('2', 'Delivery')], default=0, max_length=2, verbose_name='TIPO PAGO'),
        ),
    ]
