# Generated by Django 5.1.4 on 2025-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_type_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='type_payment_saldo',
            field=models.CharField(choices=[('0', 'Transferencia'), ('1', 'Efectivo')], default=0, max_length=2, verbose_name='TIPO PAGO SALDO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='type_invoce',
            field=models.CharField(choices=[('0', 'Boleta'), ('1', 'Factura'), ('2', 'Sin Comprobante')], default=0, max_length=2, verbose_name='TIPO'),
        ),
    ]
