# Generated by Django 5.1.4 on 2025-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_type_payment_saldo_alter_pedido_type_invoce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='saldo'),
        ),
    ]
