# Generated by Django 5.1.4 on 2025-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_saldo'),
        ('productos', '0006_alter_producto_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetail',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='pedido_details', to='productos.extra', verbose_name='Extras'),
        ),
    ]
