# Generated by Django 5.1.4 on 2025-01-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedidodetail_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_carnet',
            field=models.CharField(blank=True, max_length=50, verbose_name='carnet del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='type_payment_saldo',
            field=models.CharField(blank=True, choices=[('0', 'Transferencia'), ('1', 'Efectivo')], max_length=2, verbose_name='TIPO PAGO SALDO'),
        ),
    ]
