# Generated by Django 5.1.4 on 2025-01-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedido_cliente_carnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartp',
            name='productos_cargados',
            field=models.BooleanField(default=False, verbose_name='Productos cargados al carrito'),
        ),
    ]
