# Generated by Django 5.1.4 on 2025-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_cartp_productos_cargados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='adelanto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='ADELANTO'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_celular',
            field=models.CharField(max_length=50, verbose_name='Celular del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='DESCUENTO'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='SALDO'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='type_entrega',
            field=models.CharField(choices=[('0', 'Entrega en Tienda'), ('1', 'Envio'), ('2', 'Delivery')], default=0, max_length=2, verbose_name='METODO DE ENTREGA'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='type_payment',
            field=models.CharField(choices=[('0', 'Transferencia'), ('1', 'Efectivo')], max_length=2, verbose_name='TIPO PAGO ADELANTO'),
        ),
    ]
