# Generated by Django 5.1.4 on 2025-01-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_prod',
            field=models.ImageField(null=True, upload_to='static/img_productos'),
        ),
    ]
