# Generated by Django 5.1.4 on 2025-01-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_image_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image_prod',
            field=models.ImageField(null=True, upload_to='img_productos'),
        ),
    ]
