# Generated by Django 5.1.4 on 2025-01-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_image_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image_prod',
            new_name='image',
        ),
    ]
