# Generated by Django 5.1.4 on 2025-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_image_prod_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='extra',
            field=models.ManyToManyField(related_name='productos', to='productos.extra'),
        ),
    ]
