# Generated by Django 5.1.4 on 2025-01-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='price_purchase',
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto antes tax'),
        ),
    ]
