# Generated by Django 5.1.4 on 2025-01-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_remove_saledetail_price_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento'),
        ),
    ]
