# Generated by Django 5.1.4 on 2025-01-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
            preserve_default=False,
        ),
    ]
