# Generated by Django 5.1.4 on 2025-01-04 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_sale_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_payment',
            field=models.CharField(choices=[('0', 'Transferencia'), ('1', 'Efectivo')], max_length=2, verbose_name='TIPO PAGO'),
        ),
    ]
