# Generated by Django 5.1.4 on 2025-01-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alter_carshop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshop',
            name='user',
        ),
    ]
