# Generated by Django 5.1.4 on 2025-01-04 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_carshop_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carshop',
            unique_together={('user', 'barcode')},
        ),
    ]
