# Generated by Django 5.1.4 on 2025-01-04 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_alter_carshop_unique_together_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venta.cart', verbose_name='Carrito'),
        ),
    ]
