# Generated by Django 5.1.4 on 2025-01-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_remove_carshop_cart_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venta.cart', verbose_name='Carrito'),
        ),
    ]
