# Generated by Django 5.1.4 on 2025-01-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_carshop_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='cart',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venta.cart', verbose_name='Carrito'),
        ),
    ]
