# Generated by Django 5.1.4 on 2025-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_alter_carshop_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='barcode',
            field=models.CharField(max_length=13),
        ),
    ]
