# Generated by Django 5.1.4 on 2025-01-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_alter_carshop_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carshop',
            options={'ordering': ['-created'], 'verbose_name': 'productos del Carrito de compras', 'verbose_name_plural': 'productos del Carrito de compras'},
        ),
    ]
